version: '3'

services:
  suricata:
    build: .
    container_name: suricata
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./logs:/var/log/suricata
      - ./suricata.yaml:/etc/suricata/suricata.yaml:ro
      - ./rules:/etc/suricata/rules
    command: >
      suricata -i enp2s0 -c /etc/suricata/suricata.yaml -v
    restart: unless-stopped
